-- Phase 1 v2.1: question <-> concept many-to-many links
-- Compatible, idempotent creation for A1 graph layer.

CREATE TABLE IF NOT EXISTS public.question_concept_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  storage_key text NOT NULL,
  node_id uuid NOT NULL,
  link_type text NOT NULL DEFAULT 'primary',
  confidence real NOT NULL DEFAULT 0.5,
  source text NOT NULL DEFAULT 'auto',
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'question_concept_links_node_id_fkey'
      AND conrelid = 'public.question_concept_links'::regclass
  ) THEN
    ALTER TABLE public.question_concept_links
      ADD CONSTRAINT question_concept_links_node_id_fkey
      FOREIGN KEY (node_id) REFERENCES public.curriculum_nodes(node_id)
      ON DELETE CASCADE;
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chk_question_concept_links_link_type'
      AND conrelid = 'public.question_concept_links'::regclass
  ) THEN
    ALTER TABLE public.question_concept_links
      ADD CONSTRAINT chk_question_concept_links_link_type
      CHECK (link_type IN ('primary', 'secondary', 'prerequisite'));
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'chk_question_concept_links_confidence'
      AND conrelid = 'public.question_concept_links'::regclass
  ) THEN
    ALTER TABLE public.question_concept_links
      ADD CONSTRAINT chk_question_concept_links_confidence
      CHECK (confidence >= 0 AND confidence <= 1);
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'question_concept_links_storage_node_type_key'
      AND conrelid = 'public.question_concept_links'::regclass
  ) THEN
    ALTER TABLE public.question_concept_links
      ADD CONSTRAINT question_concept_links_storage_node_type_key
      UNIQUE (storage_key, node_id, link_type);
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_question_concept_links_storage_key
  ON public.question_concept_links(storage_key);

CREATE INDEX IF NOT EXISTS idx_question_concept_links_node_id
  ON public.question_concept_links(node_id);

CREATE INDEX IF NOT EXISTS idx_question_concept_links_source
  ON public.question_concept_links(source);

ALTER TABLE public.question_concept_links ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'question_concept_links'
      AND policyname = 'Enable read access for all users'
  ) THEN
    CREATE POLICY "Enable read access for all users"
      ON public.question_concept_links
      FOR SELECT
      USING (true);
  END IF;
END $$;

REVOKE INSERT, UPDATE, DELETE ON public.question_concept_links FROM anon, authenticated;
GRANT SELECT ON public.question_concept_links TO anon, authenticated;
